### ISSUE TITLE
Define Locale in Dockerfile

### ISSUE THREAD

**Issue by zyrolasting** [andromeda/pash#106]
My recent patch #104 came from my docker image being created such that containers start with an incorrect locale. This seems to be an artifact of how my machine interacts with Docker images if locales are not explicitly defined.

This blog posts covers the exact issue I faced, and the fix seems simple: https://leimao.github.io/blog/Docker-Locale/

But as per @angelhof's comment, I don't know to what extent this will impact EuroSys artifacts. That's why I didn't start this as a PR.

But if you all have already been using UTF-8 for everything, then doing this should not break anything.

**Comment by angelhof** [comment]
@zyrolasting I guess this is addressed by your latest PR?

**Comment by zyrolasting** [comment]
Yes. Closing.
