### ISSUE TITLE
CI code should be in new repo

### ISSUE THREAD

**Issue by zyrolasting** [andromeda/pash#118]
Since CI code is hosted in the same repository, it will run into situations like this:

```
git checkout $commit_to_test
run_tests
git checkout $commit_with_relevant_script
process_results
```

This is especially troublesome because it creates code [that would break on merge](https://github.com/andromeda/pash/blob/a0b1feb25d40ccb7c59fa5f5c74b11d65ee4ee11/scripts/remote/workers/run-perf.sh#L22).

I suggest hosting CI code separately to speed up development a bit. It takes more time to babysit something like this.

**Comment by angelhof** [comment]
That is a good point. Also I guess that CI related stuff might be better off in a private repo. @nvasilakis what do you think?

**Comment by nvasilakis** [comment]
This has been discussed offline, and we decided to move CI-related things into a new repo.
