### ISSUE TITLE
Split command

### ISSUE THREAD

**Issue by nvasilakis** [andromeda/pash#66]
This issue is for tracking progress on a new, order-aware `split` primitive that adds lightweight ordering metadata. It is expected that such a `split` will bring significant performance benefits:

* it will allow the stages after split to proceed out of order, including possibly pushing splitting/merging further down the pipeline.
* it will avoid the cost of counting of the input stream before splitting, by using a round-robin form of sharding.
* it will possibly avoid the cost of `eager`

This should help with I/O-intensive benchmarks, but also with ones that have multiple split (some of which can be avoided, as well as the stages behind them). A simple way to try this would be to use GNU `parallel` and set the `--block-size` and `-k` parameters.

**Comment by tammam1998** [comment]
Report of some of the bugs I faced and their fixes
https://www.notion.so/Bug-Reports-for-r_split-r_wrap-etc-b383eeddc9bf44b18ebae2c53ec53653

**Comment by angelhof** [comment]
Closing since it is done :)
