### ISSUE TITLE
Eager command

### ISSUE THREAD

**Issue by nvasilakis** [andromeda/pash#67]
This issue is for tracking progress regarding an improved version of `eager`. The key features include:

1. add an in-memory circular buffer; `eager` starts spilling to disk only when the buffer becomes full. 
2. add (compiler-provided) limits to both the buffer size and the disk size that `eager` can use, after which it just blocks.

(In the future, we could think about how to eliminate the double-copy to/from the circular buffer.)

The new `eager` will offer improved correctness, as now `eager` will block after some input size, maintaining the laziness features that are important in Unix commands such as `yes`. It will improve performance significantly, as now `eager` will use memory rather than disk, to store a significant fraction of the results. If the two commands connected by `eager` write and read at the same rates, `eager` should never need to touch the disk.

**Comment by tammam1998** [comment]
Will be using dgsh-tee to do 1 and 2.

Repo:
https://github.com/dspinellis/dgsh
